// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSimpleGateway creates a new instance of MockSimpleGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSimpleGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSimpleGateway {
	mock := &MockSimpleGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSimpleGateway is an autogenerated mock type for the SimpleGateway type
type MockSimpleGateway struct {
	mock.Mock
}

type MockSimpleGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSimpleGateway) EXPECT() *MockSimpleGateway_Expecter {
	return &MockSimpleGateway_Expecter{mock: &_m.Mock}
}

// DoPing provides a mock function for the type MockSimpleGateway
func (_mock *MockSimpleGateway) DoPing() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DoPing")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSimpleGateway_DoPing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoPing'
type MockSimpleGateway_DoPing_Call struct {
	*mock.Call
}

// DoPing is a helper method to define mock.On call
func (_e *MockSimpleGateway_Expecter) DoPing() *MockSimpleGateway_DoPing_Call {
	return &MockSimpleGateway_DoPing_Call{Call: _e.mock.On("DoPing")}
}

func (_c *MockSimpleGateway_DoPing_Call) Run(run func()) *MockSimpleGateway_DoPing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSimpleGateway_DoPing_Call) Return(s string) *MockSimpleGateway_DoPing_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSimpleGateway_DoPing_Call) RunAndReturn(run func() string) *MockSimpleGateway_DoPing_Call {
	_c.Call.Return(run)
	return _c
}
