// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"albums-api/internal/models"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAlbumRepository creates a new instance of MockAlbumRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlbumRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlbumRepository {
	mock := &MockAlbumRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAlbumRepository is an autogenerated mock type for the AlbumRepository type
type MockAlbumRepository struct {
	mock.Mock
}

type MockAlbumRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlbumRepository) EXPECT() *MockAlbumRepository_Expecter {
	return &MockAlbumRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAlbumRepository
func (_mock *MockAlbumRepository) Create(ctx context.Context, album models.NewAlbum) (models.Album, error) {
	ret := _mock.Called(ctx, album)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Album
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NewAlbum) (models.Album, error)); ok {
		return returnFunc(ctx, album)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NewAlbum) models.Album); ok {
		r0 = returnFunc(ctx, album)
	} else {
		r0 = ret.Get(0).(models.Album)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.NewAlbum) error); ok {
		r1 = returnFunc(ctx, album)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAlbumRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAlbumRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - album models.NewAlbum
func (_e *MockAlbumRepository_Expecter) Create(ctx any, album any) *MockAlbumRepository_Create_Call {
	return &MockAlbumRepository_Create_Call{Call: _e.mock.On("Create", ctx, album)}
}

func (_c *MockAlbumRepository_Create_Call) Run(run func(ctx context.Context, album models.NewAlbum)) *MockAlbumRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.NewAlbum
		if args[1] != nil {
			arg1 = args[1].(models.NewAlbum)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAlbumRepository_Create_Call) Return(album1 models.Album, err error) *MockAlbumRepository_Create_Call {
	_c.Call.Return(album1, err)
	return _c
}

func (_c *MockAlbumRepository_Create_Call) RunAndReturn(run func(ctx context.Context, album models.NewAlbum) (models.Album, error)) *MockAlbumRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAlbumRepository
func (_mock *MockAlbumRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAlbumRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAlbumRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockAlbumRepository_Expecter) Delete(ctx any, id any) *MockAlbumRepository_Delete_Call {
	return &MockAlbumRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAlbumRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockAlbumRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAlbumRepository_Delete_Call) Return(err error) *MockAlbumRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAlbumRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockAlbumRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockAlbumRepository
func (_mock *MockAlbumRepository) GetAll(ctx context.Context) ([]models.Album, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Album
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Album, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Album); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Album)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAlbumRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockAlbumRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlbumRepository_Expecter) GetAll(ctx any) *MockAlbumRepository_GetAll_Call {
	return &MockAlbumRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockAlbumRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockAlbumRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAlbumRepository_GetAll_Call) Return(albums []models.Album, err error) *MockAlbumRepository_GetAll_Call {
	_c.Call.Return(albums, err)
	return _c
}

func (_c *MockAlbumRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]models.Album, error)) *MockAlbumRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAlbumRepository
func (_mock *MockAlbumRepository) GetByID(ctx context.Context, id int) (models.Album, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Album
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.Album, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.Album); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Album)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAlbumRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAlbumRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockAlbumRepository_Expecter) GetByID(ctx any, id any) *MockAlbumRepository_GetByID_Call {
	return &MockAlbumRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAlbumRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockAlbumRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAlbumRepository_GetByID_Call) Return(album models.Album, err error) *MockAlbumRepository_GetByID_Call {
	_c.Call.Return(album, err)
	return _c
}

func (_c *MockAlbumRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (models.Album, error)) *MockAlbumRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAlbumRepository
func (_mock *MockAlbumRepository) Update(ctx context.Context, id int, update models.UpdateAlbum) (models.Album, error) {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Album
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.UpdateAlbum) (models.Album, error)); ok {
		return returnFunc(ctx, id, update)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.UpdateAlbum) models.Album); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Get(0).(models.Album)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.UpdateAlbum) error); ok {
		r1 = returnFunc(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAlbumRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAlbumRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - update models.UpdateAlbum
func (_e *MockAlbumRepository_Expecter) Update(ctx any, id any, update any) *MockAlbumRepository_Update_Call {
	return &MockAlbumRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockAlbumRepository_Update_Call) Run(run func(ctx context.Context, id int, update models.UpdateAlbum)) *MockAlbumRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.UpdateAlbum
		if args[2] != nil {
			arg2 = args[2].(models.UpdateAlbum)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAlbumRepository_Update_Call) Return(album models.Album, err error) *MockAlbumRepository_Update_Call {
	_c.Call.Return(album, err)
	return _c
}

func (_c *MockAlbumRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id int, update models.UpdateAlbum) (models.Album, error)) *MockAlbumRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
